// <auto-generated />
namespace SomeShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BasketModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasketModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202012192028095_BasketModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
